version: '3'

services:
  backend:
      container_name: hospitech-backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      restart: always
  frontend:
    container_name: hospitech-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
  